name: Indices zip

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Clone repository
        uses: actions/checkout@v2 

      - name: Installation de zip 
        run: sudo apt-get install zip
        
      - name: Création de l'archive
        uses: montudor/action-zip@v1
        with:
          args: zip -r indices.zip indices/  

      - name:  Ajout du fichier indices.md
        run: |
          git add indices.zip

      - name: configuration
        run: |
            git config user.name " Action Github "
            git config user.email "<>"
      - name: commit and push
         run:|
          git commit -m " Ajout de l'archive indices.zip "
          git push origin main
